nohup: ignoring input
[2023-09-21 20:15:13 +0000] [4521] [INFO] Starting gunicorn 21.2.0
[2023-09-21 20:15:13 +0000] [4521] [INFO] Listening at: http://0.0.0.0:8000 (4521)
[2023-09-21 20:15:13 +0000] [4521] [INFO] Using worker: sync
[2023-09-21 20:15:13 +0000] [4523] [INFO] Booting worker with pid: 4523
[2023-09-21 20:15:13 +0000] [4523] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/macbook/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/macbook/.local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/macbook/.local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/macbook/.local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/macbook/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/macbook/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/macbook/.local/lib/python3.8/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dlay'
[2023-09-21 20:15:13 +0000] [4523] [INFO] Worker exiting (pid: 4523)
[2023-09-21 20:15:13 +0000] [4521] [ERROR] Worker (pid:4523) exited with code 3
[2023-09-21 20:15:13 +0000] [4521] [ERROR] Shutting down: Master
[2023-09-21 20:15:13 +0000] [4521] [ERROR] Reason: Worker failed to boot.
